name: PR Comment and Diff Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  issue_comment:
    types:
      - created
      - edited

jobs:
  check-comments-and-diff:
    if: github.event.pull_request != null || github.event.issue.pull_request != null
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check for comments
      id: check-comments
      run: |
        PR_NUMBER="${{ github.event.pull_request.number || github.event.issue.number }}"
        PR_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)
        echo "$COMMENTS" > comments.json
        cat comments.json

        COMMENT_BODIES=$(echo "$COMMENTS" | jq -r '.[].body')
        echo "$COMMENT_BODIES" > comment_bodies.txt
        cat comment_bodies.txt

        COMMENT_EXISTS=$(echo "$COMMENT_BODIES" | wc -l)
        echo "comment_exists=$COMMENT_EXISTS" >> $GITHUB_ENV

        if [ "$COMMENT_EXISTS" -gt 0 ]; then
          FOUND_COMMENT=false
          LATEST_COMMENT_BODY=""
          while IFS= read -r line; do
            echo "Checking comment body: $line"
            if echo "$line" | grep -q "項目が追加されました。"; then
              FOUND_COMMENT=true
              LATEST_COMMENT_BODY="$line"
              echo "Latest relevant comment body found: $LATEST_COMMENT_BODY"
            fi
          done < comment_bodies.txt

          if [ "$FOUND_COMMENT" = true ]; then
            echo "Latest relevant comment body: $LATEST_COMMENT_BODY"
            LATEST_COMMENT_BODY=$(echo "$LATEST_COMMENT_BODY" | sed 's/\\r\\n/\n/g; s/\\n/\n/g')
            echo "Processed comment body: $LATEST_COMMENT_BODY"
            echo "$LATEST_COMMENT_BODY" | grep -q '\- \[x\] マスク不要'
            MASK_NOT_NEEDED=$?
            echo "$LATEST_COMMENT_BODY" | grep -q '\- \[x\] マスク対象登録完了'
            MASK_REGISTERED=$?
            echo "MASK_NOT_NEEDED status: $MASK_NOT_NEEDED"
            echo "MASK_REGISTERED status: $MASK_REGISTERED"
            if [ "$MASK_NOT_NEEDED" -eq 0 ] || [ "$MASK_REGISTERED" -eq 0 ]; then
              echo "mask_complete=1" >> $GITHUB_ENV
              echo "mask_complete is set to 1"
            else
              echo "どちらにもチェックがついていません"
              echo "mask_complete=0" >> $GITHUB_ENV
              echo "mask_complete is set to 0"
              exit 1
            fi
          else
            echo "対象コメントが見つかりませんでした"
            echo "mask_complete=0" >> $GITHUB_ENV
            echo "mask_complete is set to 0"
          fi
        else
          echo "コメントが存在しません"
          echo "mask_complete=0" >> $GITHUB_ENV
          echo "mask_complete is set to 0"
        fi

    - name: Compare files if no comments or incomplete mask comments
      id: compare-no-comments
      if: env.comment_exists == 'false' || (env.comment_exists == 'true' && env.mask_complete == '0')
      run: |
        echo "Comparing files because comment_exists is ${{ env.comment_exists }} and mask_complete is ${{ env.mask_complete }}"
        if ! diff sample_1.py sample_2.py > /dev/null; then
          echo "diff_exists=true" >> $GITHUB_ENV
        else
          echo "diff_exists=false" >> $GITHUB_ENV
        fi

    - name: Comment and fail if diff exists and no comments or incomplete mask comments
      if: (env.comment_exists == 'false' || (env.comment_exists == 'true' && env.mask_complete == 0)) && env.diff_exists == 'true'
      run: |
        echo "Commenting and failing because comment_exists is ${{ env.comment_exists }}, mask_complete is ${{ env.mask_complete }}, and diff_exists is ${{ env.diff_exists }}"
        PR_NUMBER="${{ github.event.pull_request.number || github.event.issue.number }}"
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"body": "項目が追加されました。\n- [ ] マスク不要\n- [ ] マスク対象登録完了"}' $COMMENT_URL
        exit 1

    - name: Exit successfully if mask complete
      if: env.mask_complete == 1
      
      run: |
        echo "Exiting successfully because mask_complete is ${{ env.mask_complete }}"
        exit 0
