name: PR Comment and Diff Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  issue_comment:
    types:
      - created

jobs:
  check-comments-and-diff:
    if: github.event.pull_request != null || github.event.issue.pull_request != null
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check for comments
      id: check-comments
      run: |
        PR_NUMBER="${{ github.event.pull_request.number || github.event.issue.number }}"
        PR_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        COMMENTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $PR_URL)
        echo "$COMMENTS" > comments.json
        cat comments.json
        COMMENT_EXISTS=$(echo "$COMMENTS" | jq '. | length > 0')
        echo "comment_exists=$COMMENT_EXISTS" >> $GITHUB_ENV
        if [ "$COMMENT_EXISTS" == "true" ]; then
          MASK_COMPLETE=$(echo "$COMMENTS" | jq -r '.[].body' | grep -F "マスク対応完了" | wc -l)
          echo "mask_complete=$MASK_COMPLETE" >> $GITHUB_ENV
        else
          echo "mask_complete=0" >> $GITHUB_ENV
        fi

    - name: Compare files if no comments or incomplete mask comments
      id: compare-no-comments
      if: env.comment_exists == 'false' || (env.comment_exists == 'true' && env.mask_complete == '0')
      run: |
        if ! diff sample_1.py sample_2.py > /dev/null; then
          echo "diff_exists=true" >> $GITHUB_ENV
        else
          echo "diff_exists=false" >> $GITHUB_ENV
        fi

    - name: Comment and fail if diff exists and no comments or incomplete mask comments
      if: (env.comment_exists == 'false' || (env.comment_exists == 'true' && env.mask_complete == 0)) && env.diff_exists == 'true'
      run: |
        PR_NUMBER="${{ github.event.pull_request.number || github.event.issue.number }}"
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"body": "- [ ] マスク不要\n- [ ] マスク対象登録完了"}' $COMMENT_URL
        exit 1

    - name: Exit successfully if mask complete
      if: env.mask_complete == '1'
      run: exit 0
